import os
import re
import uuid
import httpx
from typing import List, Dict, Any, Optional
from app.infrastructure.clients.base import IDiffusionGateway
from app.infrastructure.clients.gemini_client import GeminiVisionClient
from app.infrastructure.clients.huggingface_client import HuggingFaceClient
from app.infrastructure.storage.task_store import ITaskStore
from app.schemas.generation import GenerationDispatchRequest, GenerationDispatchResponse, GenerationStatusResponse
from app.core.supabase_client import get_supabase_admin
from app.core.logging import logger

class GenerationService:
    def __init__(
        self,
        diffusion_gateway: IDiffusionGateway,
        task_store: ITaskStore,
        gemini_vision: Optional[GeminiVisionClient] = None,
        hf_client: Optional[HuggingFaceClient] = None
    ):
        self.diffusion_gateway = diffusion_gateway
        self.task_store = task_store
        self.gemini_vision = gemini_vision or GeminiVisionClient()
        self.hf_client = hf_client or HuggingFaceClient()

    async def _upload_to_supabase_storage(self, image_bytes: bytes, file_prefix: str = "gen") -> Optional[str]:
        """Uploads generated bytes to Supabase user_generations bucket and returns public URL."""
        try:
            admin = get_supabase_admin()
            file_name = f"generations/{file_prefix}_{uuid.uuid4().hex}.png"
            admin.storage.from_("user_generations").upload(
                file_name,
                image_bytes,
                {"content-type": "image/png"}
            )
            return admin.storage.from_("user_generations").get_public_url(file_name)
        except Exception as e:
            logger.error(f"[Storage] Failed to upload generated image to Supabase: {e}")
            return None

    async def dispatch(self, req: GenerationDispatchRequest, user_id: Optional[str] = None) -> GenerationDispatchResponse:
        task_id = f"gen_{os.urandom(4).hex()}"
        has_face_lock = bool(req.face_reference_urls and len(req.face_reference_urls) > 0) or bool(req.character_id)
        effective_prompt = req.prompt.strip()

        # ── 1. Multimodal Facial Identity Conditioning ────────────────────────
        extracted_face_tokens = None
        ref_url = None
        if req.face_reference_urls and len(req.face_reference_urls) > 0:
            ref_url = req.face_reference_urls[0]
            try:
                logger.info(f"[Face-Lock] Downloading reference selfie for facial conditioning: {ref_url}")
                async with httpx.AsyncClient(timeout=10.0) as client:
                    img_resp = await client.get(ref_url)
                    if img_resp.status_code == 200:
                        mime = img_resp.headers.get("content-type", "image/png").split(";")[0]
                        extracted_face_tokens = await self.gemini_vision.extract_facial_identity(
                            img_resp.content, mime_type=mime
                        )
                    else:
                        logger.warning(f"[Face-Lock] Reference photo download returned HTTP {img_resp.status_code}")
            except Exception as e:
                logger.error(f"[Face-Lock] Error extracting facial identity: {e}")

        if extracted_face_tokens:
            cleaned = re.sub(r'^(using\s+(my\s+)?(uploaded\s+)?photo(\s*,)?\s*)', '', effective_prompt, flags=re.IGNORECASE)
            cleaned = re.sub(r'preserve\s+my\s+identity(\s*,)?\s*', '', cleaned, flags=re.IGNORECASE)
            effective_prompt = f"Portrait of a {extracted_face_tokens}, {cleaned.strip()}"
            logger.info(f"[Face-Lock] Synthesized identity-conditioned prompt: {effective_prompt[:150]}...")

        # ── 2. Route Generation Engine (Hugging Face InstantID vs FLUX.1) ─────
        direct_url = None
        tier_label = "Tier 0 (FLUX.1-schnell via Hugging Face)"

        if has_face_lock and ref_url:
            tier_label = "Tier 1 (InstantID Face-Lock via Hugging Face)"
            try:
                logger.info("[Generation] Invoking Hugging Face InstantID for 100% Face Preservation...")
                instant_bytes = await self.hf_client.generate_instantid(
                    face_image_url_or_path=ref_url,
                    prompt=effective_prompt,
                    seed=req.seed or 42
                )
                if instant_bytes:
                    direct_url = await self._upload_to_supabase_storage(instant_bytes, file_prefix="instantid")
                    if direct_url:
                        logger.info(f"[Generation] InstantID successfully uploaded: {direct_url}")
            except Exception as e:
                logger.error(f"[Generation] InstantID generation encountered error: {e}")
        else:
            try:
                logger.info("[Generation] Invoking Hugging Face FLUX.1-schnell for Text-to-Image...")
                flux_bytes = await self.hf_client.generate_flux(
                    prompt=effective_prompt,
                    width=req.width or 1024,
                    height=req.height or 1024,
                    seed=req.seed or 42
                )
                if flux_bytes:
                    direct_url = await self._upload_to_supabase_storage(flux_bytes, file_prefix="flux")
                    if direct_url:
                        logger.info(f"[Generation] FLUX.1 successfully uploaded: {direct_url}")
            except Exception as e:
                logger.error(f"[Generation] FLUX.1 generation encountered error: {e}")

        # Fallback to direct safe URL if cloud generation did not return a permanent URL
        if not direct_url:
            logger.warning("[Generation] Hugging Face generation unavailable, falling back to safe gateway...")
            direct_url = self.diffusion_gateway.build_safe_url(
                prompt=effective_prompt,
                width=req.width or 1024,
                height=req.height or 1024,
                seed=req.seed or 42,
                model="flux"
            )

        # ── 3. Record Task in State Store ─────────────────────────────────────
        self.task_store.save_task(task_id, {
            "tier": tier_label,
            "status": "completed",
            "progress": 100,
            "output_url": direct_url,
            "prompt": effective_prompt,
            "has_face_lock": has_face_lock,
            "extracted_features": extracted_face_tokens
        })

        # ── 4. Cloud Persistence: Attempt Supabase Jobs Table Insert ──────────
        if user_id and user_id != "00000000-0000-0000-0000-000000000000":
            try:
                admin = get_supabase_admin()
                admin.table("jobs").insert({
                    "job_id": task_id,
                    "user_id": user_id,
                    "type": "IMAGE_GEN",
                    "status": "completed",
                    "prompt": effective_prompt,
                    "preview_url": direct_url,
                    "credits_deducted": 3.0 if has_face_lock else 2.0,
                    "is_download_unlocked": False
                }).execute()
                logger.info(f"[Cloud Jobs] Persisted generation {task_id} for user {user_id}")
            except Exception as e:
                logger.debug(f"[Cloud Jobs] Table save skipped or pending migration: {e}")

        return GenerationDispatchResponse(
            task_id=task_id,
            tier=tier_label,
            status="ready",
            estimated_seconds=18 if has_face_lock else 5,
            direct_image_url=direct_url
        )

    def get_status(self, task_id: str) -> GenerationStatusResponse:
        task = self.task_store.get_task(task_id)
        if not task:
            fallback_url = self.diffusion_gateway.build_safe_url("cyberpunk visual masterpiece")
            return GenerationStatusResponse(
                task_id=task_id,
                status="completed",
                progress=100,
                output_url=fallback_url
            )
        return GenerationStatusResponse(
            task_id=task_id,
            status=task.get("status", "unknown"),
            progress=task.get("progress", 0),
            output_url=task.get("output_url")
        )

    def get_websocket_phases(self, task_id: str) -> List[Dict[str, Any]]:
        task = self.task_store.get_task(task_id) or {}
        has_face_lock = task.get("has_face_lock", False)

        if has_face_lock:
            return [
                {"progress": 20, "status": "scanning_face", "message": "Gemini 2.5 Flash scanning facial contours..."},
                {"progress": 50, "status": "locking_identity", "message": "InstantID locking 512-D identity vectors..."},
                {"progress": 80, "status": "rendering", "message": "Synthesizing styled portrait with preserved identity..."},
                {"progress": 100, "status": "completed", "message": "Identity-locked master rendered!"}
            ]
        else:
            return [
                {"progress": 20, "status": "queued", "message": "Dispatching to FLUX.1 engine..."},
                {"progress": 50, "status": "compiling", "message": "Compiling diffusion prompt tokens..."},
                {"progress": 80, "status": "diffusing", "message": "FLUX.1-schnell denoising 1024x1024 latents..."},
                {"progress": 100, "status": "completed", "message": "High-fidelity FLUX visual complete!"}
            ]
